[env:m5stick-s3]
platform = https://github.com/m5stack/platform-espressif32.git
board = m5stick-s3
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.filesystem = littlefs
board_build.partitions = no_ota.csv
board_build.f_cpu = 160000000L
board_build.arduino.memory_type = qio_opi
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
build_unflags = -std=gnu++11
build_src_filter = +<*> +<buddies/>
lib_deps =
    m5stack/M5Unified @ ^0.2.12
    bitbank2/AnimatedGIF @ ^2.1.1
    bblanchon/ArduinoJson @ ^7.0.0
    knolleary/PubSubClient @ ^2.8
